/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const WallpaperType = IDL.Variant({
  'live' : IDL.Null,
  'twoD' : IDL.Null,
  'threeD' : IDL.Null,
});
export const WallpaperMeta = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'thumbnail' : IDL.Text,
  'preview' : IDL.Text,
  'wType' : WallpaperType,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFavorite' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFavorites' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getWallpaperCatalog' : IDL.Func([], [IDL.Vec(WallpaperMeta)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFavorite' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'removeFavorite' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const WallpaperType = IDL.Variant({
    'live' : IDL.Null,
    'twoD' : IDL.Null,
    'threeD' : IDL.Null,
  });
  const WallpaperMeta = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'thumbnail' : IDL.Text,
    'preview' : IDL.Text,
    'wType' : WallpaperType,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFavorite' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFavorites' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getWallpaperCatalog' : IDL.Func([], [IDL.Vec(WallpaperMeta)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFavorite' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'removeFavorite' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };